### ISSUE TITLE
How to import this file to become a bookmark for another browser?

### ISSUE THREAD

**Issue by hrayes** [asheroto/Extension-Exporter#5]
### Describe the feature or improvement you're requesting

excellent project and it is helpful to keep track of the extension, but is there a way to import this file into the same browser or another browser as a bookmark?

**Comment by hrayes** [comment]
sorry, when i watched the video, i can add the extensions one at a time.
excellent work asheroto
Thank you!

**Comment by asheroto** [comment]
That's a great idea! Like an export file that you can import automatically into the new browser.

I wish there was some way to automatically install extensions but Chrome security restrictions prevent one extension from installing another. Bummer. :-/

Otherwise that would be a really good idea.

For now, you can open the HTML file in the other browser, then click each extension and install. 

If their policies change or there becomes a new way to do this we can reopen the issue.

**Comment by asheroto** [comment]
Just re-read your comment. Creating bookmarks might be a solution here. It could create an HTML file which could then be imported into another browser.

Is that something like you were thinking?
