### ISSUE TITLE
[Request]: add installation/update date in report

### ISSUE THREAD

**Issue by wjharing** [asheroto/Extension-Exporter#6]
### Describe the feature or improvement you're requesting

It is very helpful to understand when the extensions have been updated for the last time. I believe there is some kind of installation_date stored somewhere?
(this will also help to identify which extensions are old and no longer maintained)

**Comment by asheroto** [comment]
That's a great idea, I'd love to implement it, however I haven't been able to locate any documentation that allows access to the installation date through the API.

When researching this, I can't find any way to grab the install date except by manually reading the metadata of an extension's folder, which is not possible with a Chrome extension.

I wish Google would add this because I'd love to know when the extensions are installed or updated.

I'm going to close this for now but let me know if you find some way I missed.
